server:
  port: 8080

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    format_sql: true





